### PR TITLE
Added Linux Progs.

### PR DESCRIPTION
**Pull request by shikhar-scs**
Several Simple Ubuntu programs have been added with instructions for running them. Get started now. :slightly_smiling_face:

### CODE REVIEW

**Review by PikkaPikkachu — COMMENTED** [review]
Are these Ubuntu specific programs only? Wouldn't they work on any LINUX OS?

**Comment by shikhar-scs** [comment]
Well, these programs will work on dosbox. So they work on Mac too (tried and tested). And yep they'll also work on the `emu8086`. So yep, we can change ubuntu to Linux.

**Review by PikkaPikkachu — CHANGES_REQUESTED** [review]
Can you change the name of directory to Linux?

**Comment by PikkaPikkachu** [comment]
DOS Box is based on the operating system DOS. So the systems having support for DOS will run DOS programs. The programs you have written probably do not use OS X system calls, but rather depend on DOS API calls, that's why they will run on Mac system with DOS installed.

**Review by PikkaPikkachu — COMMENTED** [review]
1. Remove the emoji from README
2. Under "Setup" create a section for "Mac" and "Linux"
3. Add "Linux" instructions under the "Linux" section 
4. Remove "Assembly-with-MacOS.iml", "jsLibraryMappings.xml", "modules.xml", "workspace.xml" files and all other files ending in .xml and .iml

**Comment by shikhar-scs** [comment]
>  The programs you have written probably do not use OS X system calls,

Yep of course. 

> depend on DOS API calls,

Yep. Works on windows too :grin:

**Comment by PikkaPikkachu** [comment]
It is also preferable that you squash these commits into one please. Trying to avoid messy work. :)

**Comment by shikhar-scs** [comment]
All tasks done and squashed my commits too :sweat_smile: .

Note : Merge commits can't be squashed. And the first one is a joint commit. You can try squash and merge though. 

Anything else ?

**Review by PikkaPikkachu — APPROVED** [review]
Looks good.

**Comment by shikhar-scs** [comment]
Yayy!! Thanks

**Comment by himanish-star** [comment]
> Note : Merge commits can't be squashed. And the first one is a joint commit. You can try squash and merge though.

They can be rebased :expressionless: 

Anyway thanks for the code @shikhar-scs :tada: A real help for exams :stuck_out_tongue_winking_eye:

**Pull request merged**
